Create Beacon Bridge Project
Health-Informatics-UoN/beacon-tools pull request #8
Opened 2024-02-26 16:58 UTC by vpnu

## Pull Request Contents

| |
|-|
🛠️ Repo maintenance

## Description

- Create an ASP.NET Core Web API Project targeting .NET 8 BeaconBridge
- Create xunit project BeaconBridge.Tests

## Related Issues or other material

- [ ] This PR relates to one or more issues, detailed below

#2 

- Related Issue #
- Closes #2 

## [optional] What gif best describes this PR or how it makes you feel?

![alt_text](https://media.giphy.com/media/LlyclUtYHyz8A/giphy.gif)

- [x] I've completed all **actions** and **tasks** detailed in the PR Template

2024-02-26 17:03 UTC, dcl10 commented on app/BeaconBridge/BeaconBridge.http
Is this one of the template files that we don't actually need?

2024-02-27 09:40 UTC, dcl10 approved these changes

2024-02-27 13:55 UTC, beforan requested changes

2024-02-27 13:55 UTC, beforan commented on app/BeaconBridge/Properties/launchSettings.json
> +  },
```suggestion
```
Don't need the IIS profile; in fact I'd prefer not to have it and naturally have all users run Kestrel

2024-02-27 13:55 UTC, beforan commented on app/BeaconBridge/Properties/launchSettings.json
> +    }
```suggestion
```
Don't need the IIS profile; in fact I'd prefer not to have it and naturally have all users run Kestrel

2024-02-27 15:13 UTC, beforan approved these changes

2024-02-28 09:53 UTC, dcl10 approved these changes

2024-02-28 09:53 UTC, merged